---

info:
  description: Training configuration repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://euruser:eurpass@eurekasvr-jcabuhat.cfapps.io/eureka
---


spring:
  profiles: cloud
  
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
